### ISSUE TITLE
Worker - TODO

### ISSUE THREAD

**Issue by deepakduggirala** [IUSCA/bioloop#34]
Workers:
- [x] embellish workflow, step, task objects with explicit statuses, start and end times, progress, etc which are implicitly stored in order of tasks, task attributes.
- [x] docker for workflow server
- [x] pm2 config for daemon processes - auto start, background
- [x] add /health
- [x] If the API call fails at the end of the task, do not retry the entire task. This could happen when the API is momentarily down.
- [x] isolate workflow steps into a config (todo in api too)
- [x] use a hook to write task status to result backend as soon as it starts, otherwise a task object is not created in the result backend until either the task succeeds or fails or an status update from task code.
- [x] In workflow code: handle gracefully if a task is not found
- [x] Enable pm2 to start services automatically if the server restarts. - not possible in colo23?
- [ ] Change in get workflow api, instead of last_task_run and prev_task_runs, return task_runs as an array sorted chronologically. change the query to num_task_runs, with -1 representing all tasks.
- [ ] workflow resume: if the pending step is not the first step, and it has never run before, then get the args from the previous step.
- [x] celery: read more about inbuilt workers in celery that clean up tasks periodically
- [x] celery config for long running tasks, a worker cannot claim / preprocess, acks late, etc
  - [x] documentation on resiliency - task level, worker level
- [x] Design WorkflowTask to not retry on Custom Exception (nonRetryableException) - https://github.com/celery/celery/blob/b4d23f290713ebea25ab517d9f980ae542885577/celery/app/autoretry.py#L14
- [x] Make a list of all the config that can be configured on the task, and how to overwrite the config on the WorkflowTask.
- [x] Update task code without restarting the celery worker
- [x] Application specific queues
- [x] Standardize status and status sets names across layers
- [ ] error which caused the task to be retried is lost when the task sends progress updates / on success.
- [ ] Add options to reject task and mark as to be skipped. When the workflow resumes, it should execute next step. (This is helpful when the task is manually completed, and workflow has to complete remaining steps). When the task is truly lazy, it will see that the desired state is already reached, it does nothing and completes. But for non-lazy tasks, this is required.
- [x] await stability being a task is not an efficient design. When there are multiple concurrent data ingestion, most of the celery tasks will be idle waiting for stability of some datasets while inspect, archive tasks of other ready datasets will be waiting in the queue. Move await stability functionality to watch where in one loop all the datasets can be checked at once.

Logging
  - [x] use celery logger
  - [ ] log file management, rotation for each task
  - [ ] Include filename and line number - celery logger formatter
  - [ ] use python logger instead of print in register.py and app.py

Config
  - [x] hierarchical config - for dev and prod envs
  - [x] refactor celeryconfig to use data from main config
